name: Python testing

on:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - master
      - release
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Hussain Rifad
      uses: actions/hussainrifad

    - name: Print user info
      run: |
        echo "ФИО: Hussain Rifad"
        echo "Номер группы: 3114"
        echo "GitHub Nickname: $GITHUB_ACTOR"

    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests with pytest
      run: |
        pytest

    - name: Check code style with flake8
      run: |
        pip install flake8
        flake8 .

    - name: Format code with black (optional)
      run: |
        pip install black
        black .
