name: Python test

on:
  push:
    branches:
      - master
      - release/*
  pull_request:
    branches:
      - master
      - release/*
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      FULL_NAME: "Hussain Rifad"
      GROUP_NUMBER: "M3113"

    steps:
      # 1. Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Print personal info
      - name: Print Personal Info
        run: |
          echo "Author: ${{ env.NAME }}"
          echo "Group: ${{ env.GROUP }}"
          echo "GitHub username: ${{ github.actor }}"

      # 3. Set up Python 3.13
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      # 4. Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 5. Run unit tests
      - name: Run Tests
        run: pytest

      # 6. Run linter for code style
      - name: Lint Code
        run: flake8 . --count --max-line-length=88 --show-source --statistics
